### ISSUE TITLE
Bug: Segfault in notifier thread PING

### ISSUE THREAD

**Issue by hbeni** [hbeni/fgcom-mumble#138]
Segfault in notifier thread

Note also the `[GC]` cleanout. Why does it suddenly see outdated local data for >600 seconds!?

Affected/triggering line:
https://github.com/hbeni/fgcom-mumble/blob/a8bd706e0d35ee190b506f018a25d329bb3ba0da/client/mumble-plugin/lib/io_plugin.cpp#L271
![grafik](https://user-images.githubusercontent.com/13608602/125647103-f17f55e6-7d0f-479f-8603-3a2414650c88.png)
![grafik](https://user-images.githubusercontent.com/13608602/125645097-d3e31715-de16-4bb6-966f-c3c77ceec258.png)

----
Also a little more context:
- client run about half an hour
- connected where 30 bots
- The terminal reported callsign in LCL-State was slow to change. Without clients its crisp fast.

**Comment by hbeni** [comment]
@krzmbrzl
Sorry! to bother again.
I'm a little confused. That code did work for a longer time, and now it segaults sporadically.
Am I checking wrongly for error?

**Comment by Krzmbrzl** [comment]
I recently made some changes to how the synchronization of API calls works. It seems that this is probably responsible for the segfault you are seeing. The only issue is: I don't understand why it would segfault...

EDIT: Actually after having stared at the code for a while I might have found a problem with it. It doesn't seem to explain why the Segfault would happen at the position it did but then again C++ can be a bit weird when it comes to where the error actually causes a crash. I'll create a PR with the fix and then you can test against that build to see if the issue persists :)

**Comment by hbeni** [comment]
Robert, again, you are my hero.
I can't express how thankful I am that you aren't annoyed of me yet. I am feeling shame that I don't grasp C/C++ things better by now. Those bugs I always seem to dig out are so hard to reproduce and see and get an Idea of what's going on. It feels a lot like fishing in gloomy waters.
And I'm sorry, that I cause you so much trouble.

**Comment by Krzmbrzl** [comment]
Note however that if this is indeed the cause of the issue, then it seems that your plugin has produced a deadlock again (which thanks to the new mechanic will not result in an actual deadlock though but instead returns after some time with a timeout error code).

Thus if the crash is fixed by this, you should search for timeout error codes being returned to you.

**Comment by Krzmbrzl** [comment]
-> https://github.com/mumble-voip/mumble/pull/5188

**Comment by Krzmbrzl** [comment]
> Robert, again, you are my hero.
I can't express how thankful I am that you aren't annoyed of me yet. I am feeling shame that I don't grasp C/C++ things better by now. Those bugs I always seem to dig out are so hard to reproduce and see and get an Idea of what's going on. It feels a lot like fishing in gloomy waters.
And I'm sorry, that I cause you so much trouble.

Thanks for the kind words :blush: 
Don't feel troubled asking things like this though. First of all you have been and continue to be a huge contribution in making the plugin API more stable and usable thanks to your continuous tests and reports. And secondly: C++ is a bitch and it took me quite some time to get to where I am now in terms of proficiency with this language and still I quite often look at my screen without the slightest idea what is going on - so this is nothing to be ashamed about :sweat_smile:

So in that sense: Please keep "troubling" me so that in the end the plugin API will end up being as good as it can be :D

**Comment by hbeni** [comment]
That was a huge relieve to read.
Thank you :D <3

**Comment by hbeni** [comment]
Just tested a little. All went good until the GUI hang again (still with my last mumble checkout, so not your fixes yet).
It hang with disabled GarbageCollector, so that was not the main cause.

**Comment by hbeni** [comment]
Seems to be fixed by mumble-voip/mumble#5188
